<a href="https://colab.research.google.com/github/simmiagarwal60/AI-ML-Projects/blob/main/Emotions_NLP_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.read_csv("train.txt", sep = ';', header= None, names = ['text', 'emotion'])

In [46]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [47]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [48]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i=0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i += 1

In [49]:
emotion_numbers

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [50]:
df['emotion'] = df['emotion'].map(emotion_numbers)

In [51]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

# Text Cleaning

1. LowerCasing

In [52]:
df['text'] = df['text'].apply(lambda x: x.lower())

2. Remove Punctuation

In [53]:
import string
def remove_punc(text):
  return text.translate(str.maketrans('', '', string.punctuation))

In [54]:
df['text'] = df['text'].apply(remove_punc)

3. Remove Digits

In [55]:
def remove_digits(text):
  new = ""
  for i in text:
    if not i.isdigit():
      new += i
  return new

df['text'] = df['text'].apply(remove_digits)

4. Remove emojis or special characters

In [56]:
def remove_emojis(text):
  new = ""
  for i in text:
    if i.isascii():
      new += i
  return new

df['text'] = df['text'].apply(remove_emojis)

In [57]:
import nltk

In [58]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [59]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [60]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [61]:
def remove_stopwords(text):
  words = word_tokenize(text)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [62]:
df['text'] = df['text'].apply(remove_stopwords)

In [63]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [64]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [66]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

In [67]:
df.shape

(16000, 2)

In [68]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [69]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116049 stored elements and shape (12800, 13359)>

In [70]:
X_test_bow = bow_vectorizer.transform(X_test)

In [71]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [72]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [73]:
pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.7678125

In [74]:
tfidf_vectorizer = TfidfVectorizer()

In [83]:
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [85]:
y_pred_tfidf = nb2_model.predict(X_test_tfidf)
print(accuracy_score(y_test, y_pred_tfidf))

0.6609375

In [95]:
from sklearn.linear_model import LogisticRegression
model_lr = LogisticRegression(max_iter = 1000)
model_lr.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [96]:
y_pred_lr = model_lr.predict(X_test_tfidf)
print(accuracy_score(y_test, y_pred_lr))

0.8615625